modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
[[mods]]

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Palm3"
description='''
Adds dimmable versions of cage lamps from Create: Deco.
'''
logoFile= "icon.png"
displayURL="https://modrinth.com/mod/create-ddcl"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="[6.0.7, )"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="createdeco"
type="required"
versionRange="[2.1.0,)"
ordering="AFTER"
side="BOTH"
